export const CALL_TENANT_REQUEST = 'CALL_TENANT_REQUEST'
export const CALL_TENANT = 'CALL_TENANT'
export const CALL_TENANT_FAIL = 'CALL_TENANT_FAIL'

export const CALL_MENU_REQUEST = 'CALL_MENU_REQUEST'
export const CALL_MENU = 'CALL_MENU'
export const CALL_MENU_FAIL = 'CALL_MENU_FAIL'

export const CLEAR_MENU = 'CLEAR_MENU'

export const CALL_SUBMENU_REQUEST = 'CALL_SUBMENU_REQUEST'
export const CALL_SUBMENU = 'CALL_SUBMENU'
export const CALL_SUBMENU_FAIL = 'CALL_SUBMENU_FAIL'

export const CLEAR_SUBMENU = 'CLEAR_SUBMENU'
