export const MENU_SUBMENU_LIST_REQUEST = 'MENU_SUBMENU_LIST_REQUEST'
export const MENU_SUBMENU_LIST = 'MENU_SUBMENU_LIST'
export const MENU_SUBMENU_LIST_FAIL = 'MENU_SUBMENU_LIST_FAIL'
export const MENU_SUBMENU_LIST_RESET = 'MENU_SUBMENU_LIST_RESET'

export const MENU_SUBMENU_DELETE_REQUEST = 'MENU_SUBMENU_DELETE_REQUEST'
export const MENU_SUBMENU_DELETE = 'MENU_SUBMENU_DELETE'
export const MENU_SUBMENU_DELETE_FAIL = 'MENU_SUBMENU_DELETE_FAIL'
export const MENU_SUBMENU_DELETE_RESET = 'MENU_SUBMENU_DELETE_RESET'

export const MENU_SUBMENU_RESET = 'MENU_SUBMENU_RESET'

export const MENU_SUBMENU_CREATE_REQUEST = 'MENU_SUBMENU_CREATE_REQUEST'
export const MENU_SUBMENU_CREATE = 'MENU_SUBMENU_CREATE'
export const MENU_SUBMENU_CREATE_FAIL = 'MENU_SUBMENU_CREATE_FAIL'
export const MENU_SUBMENU_CREATE_RESET = 'MENU_SUBMENU_CREATE_RESET'

export const MENU_SUBMENU_EDIT_REQUEST = 'MENU_SUBMENU_EDIT_REQUEST'
export const MENU_SUBMENU_EDIT = 'MENU_SUBMENU_EDIT'
export const MENU_SUBMENU_EDIT_FAIL = 'MENU_SUBMENU_EDIT_FAIL'
export const MENU_SUBMENU_EDITABLE = 'MENU_SUBMENU_EDITABLE'

export const MENU_SUBMENU_UPDATE_REQUEST = 'MENU_SUBMENU_UPDATE_REQUEST'
export const MENU_SUBMENU_UPDATE = 'MENU_SUBMENU_UPDATE'
export const MENU_SUBMENU_UPDATE_FAIL = 'MENU_SUBMENU_UPDATE_FAIL'
export const MENU_SUBMENU_UPDATE_RESET = 'MENU_SUBMENU_UPDATE_RESET'