export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE = 'ORDER_CREATE'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const ORDER_DELETE = 'ORDER_DELETE'
export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET'

export const ORDER_MENU_DELETE = 'ORDER_MENU_DELETE'
export const ORDER_MENU_DELETE_RESET = 'ORDER_MENU_DELETE_RESET'

export const ORDER_PAID_REQUEST = 'ORDER_PAID_REQUEST'
export const ORDER_PAID = 'ORDER_PAID'
export const ORDER_PAID_RESET = 'ORDER_PAID_RESET'

export const ORDER_PAID_TABLE_REQUEST = 'ORDER_PAID_TABLE_REQUEST'
export const ORDER_PAID_TABLE = 'ORDER_PAID_TABLE'
export const ORDER_PAID_RESET_TABLE = 'ORDER_PAID_RESET_TABLE'

export const ORDER_PAID_PO_REQUEST = 'ORDER_PAID_PO_REQUEST'
export const ORDER_PAID_PO = 'ORDER_PAID_PO'
export const ORDER_PAID_RESET_PO = 'ORDER_PAID_RESET_PO'

export const ORDER_PAID_HIS_REQUEST = 'ORDER_PAID_HIS_REQUEST'
export const ORDER_PAID_HIS = 'ORDER_PAID_HIS'
export const ORDER_PAID_RESET_HIS = 'ORDER_PAID_RESET_HIS'

export const ORDER_TABLE_REQUEST = 'ORDER_TABLE_REQUEST'
export const ORDER_TABLE = 'ORDER_TABLE'
export const ORDER_PAID_EMPTY = 'ORDER_PAID_EMPTY'

export const ORDER_TENANT_REQUEST = 'ORDER_TENANT_REQUEST'
export const ORDER_TENANT = 'ORDER_TENANT'
export const ORDER_TENANT_EMPTY = 'ORDER_TENANT_EMPTY'

export const ORDER_TAMBAH_TABLE_REQUEST = 'ORDER_TAMBAH_TABLE_REQUEST'
export const ORDER_TAMBAH_TABLE = 'ORDER_TAMBAH_TABLE'
export const ORDER_PAID_TAMBAH_EMPTY = 'ORDER_PAID_TAMBAH_EMPTY'

export const ORDER_STATUS_REQUEST = 'ORDER_STATUS_REQUEST'
export const ORDER_STATUS = 'ORDER_STATUS'
export const ORDER_RESET = 'ORDER_RESET'


export const ORDER_PAID_DETAIL_REQUEST = 'ORDER_PAID_DETAIL_REQUEST'
export const ORDER_PAID_DETAIL = 'ORDER_PAID_DETAIL'
export const ORDER_PAID_DETAIL_RESET = 'ORDER_PAID_DETAIL_RESET'

export const ORDER_CHART_WHOLE_REQUEST = 'ORDER_CHART_WHOLE_REQUEST'
export const ORDER_CHART_WHOLE = 'ORDER_CHART_WHOLE'
export const ORDER_CHART_WHOLE_RESET = 'ORDER_CHART_WHOLE_RESET'

export const ORDER_CHART_TENANT_REQUEST = 'ORDER_CHART_TENANT_REQUEST'
export const ORDER_CHART_TENANT = 'ORDER_CHART_TENANT'
export const ORDER_CHART_TENANT_RESET = 'ORDER_CHART_TENANT_RESET'