export const TABLE_LIST_REQUEST = 'TABLE_LIST_REQUEST'
export const TABLE_LIST = 'TABLE_LIST'
export const TABLE_LIST_RESET = 'TABLE_LIST_RESET'

export const TABLE_LIST_READY_REQUEST = 'TABLE_LIST_READY_REQUEST'
export const TABLE_LIST_READY = 'TABLE_LIST_READY'
export const TABLE_LIST_READY_RESET = 'TABLE_LIST_READY_RESET'

export const TABLE_LIST_ID_REQUEST = 'TABLE_LIST_ID_REQUEST'
export const TABLE_LIST_ID = 'TABLE_LIST_ID'
export const TABLE_LIST_ID_RESET = 'TABLE_LIST_ID_RESET'

export const TABLE_STATUS_REQUEST = 'TABLE_STATUS_REQUEST'
export const TABLE_STATUS = 'TABLE_STATUS'
export const TABLE_STATUS_RESET = 'TABLE_STATUS_RESET'

export const TABLE_DELETE_REQUEST = 'TABLE_DELETE_REQUEST'
export const TABLE_DELETE = 'TABLE_DELETE'
export const TABLE_DELETE_RESET = 'TABLE_DELETE_RESET'

export const TABLE_RESET = 'TABLE_RESET'

export const TABLE_CREATE_REQUEST = 'TABLE_CREATE_REQUEST'
export const TABLE_CREATE = 'TABLE_CREATE'
export const TABLE_CREATE_RESET = 'TABLE_CREATE_RESET'


export const TABLE_EDIT = 'TABLE_EDIT'
export const TABLE_EDITABLE = 'TABLE_EDITABLE'

export const TABLE_UPDATE_REQUEST = 'TABLE_UPDATE_REQUEST'
export const TABLE_UPDATE = 'TABLE_UPDATE'
export const TABLE_UPDATE_RESET = 'TABLE_UPDATE_RESET'