export const MENU_LIST_REQUEST = 'MENU_LIST_REQUEST'
export const MENU_LIST = 'MENU_LIST'
export const MENU_LIST_RESET = 'MENU_LIST_RESET'

export const MENU_DELETE_REQUEST = 'MENU_DELETE_REQUEST'
export const MENU_DELETE = 'MENU_DELETE'
export const MENU_RESET = 'MENU_RESET'


export const MENU_CREATE_REQUEST = 'MENU_CREATE_REQUESTV'
export const MENU_CREATE = 'MENU_CREATE'
export const MENU_CREATE_RESET = 'MENU_CREATE_RESET'

export const MENU_EDIT = 'MENU_EDIT'
export const MENU_EDITABLE = 'MENU_EDITABLE'

export const MENU_UPDATE_REQUEST = 'MENU_UPDATE_REQUEST'
export const MENU_UPDATE_RESET = 'MENU_UPDATE_RESET'

export const MENU_LIST_ID_REQUEST = 'MENU_LIST_ID_REQUEST'
export const MENU_LIST_ID = 'MENU_LIST_ID'
export const MENU_LIST_ID_RESET = 'MENU_LIST_ID_RESET'