export const TENANT_LIST_REQUEST = 'TENANT_LIST_REQUEST'
export const TENANT_LIST = 'TENANT_LIST'
export const TENANT_LIST_RESET = 'TENANT_LIST_RESET'

export const TENANT_LIST_ID_REQUEST = 'TENANT_LIST_ID_REQUEST'
export const TENANT_LIST_ID = 'TENANT_LIST_ID'
export const TENANT_LIST_ID_RESET = 'TENANT_LIST_ID_RESET'

export const TENANT_DELETE_REQUEST = 'TENANT_DELETE_REQUEST'
export const TENANT_DELETE = 'TENANT_DELETE'
export const TENANT_DELETE_RESET = 'TENANT_DELETE_RESET'

export const TENANT_RESET = 'TENANT_RESET'

export const TENANT_CREATE_REQUEST = 'TENANT_CREATE_REQUEST'
export const TENANT_CREATE = 'TENANT_CREATE'
export const TENANT_CREATE_RESET = 'TENANT_CREATE_RESET'


export const TENANT_EDIT = 'TENANT_EDIT'
export const TENANT_EDITABLE = 'TENANT_EDITABLE'

export const TENANT_UPDATE_REQUEST = 'TENANT_UPDATE_REQUEST'
export const TENANT_UPDATE = 'TENANT_UPDATE'
export const TENANT_UPDATE_RESET = 'TENANT_UPDATE_RESET'